MEMORY_ACCESS = 1
REFRESH = 2
TRR_LOOKUP = 3
PARA_CHECK_PROBABILITY = 4
BIT_FLIP = 5
TRR_REFRESH = 6
PARA_ROW_ACTIVATION = 7
HAMMER_STATIC = 8
HAMMER_PATTERN = 9
LOG = 10

# Custom operations
ARAR_LOOKUP = 11
ARAR_CHECK_PROBABILITY = 12
ARAR_CALCULATE_PROBABILITY = 13
ARAR_ROW_ACTIVATION = 14